from faker import Faker
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import ParagraphStyle
import random

fake = Faker()

# Define pools of potential values for each section
indications_pool = [
    "Abdominal pain",
    "Family history of colorectal cancer",
    "Change in bowel habits",
    "Anemia",
    "Positive fecal occult blood test",
    "Rectal bleeding",
    "Unexplained weight loss",
    "Iron deficiency anemia",
    "Suspected inflammatory bowel disease (IBD)",
    "Screening for colorectal cancer",
    "Surveillance for high-risk patients",
    "Follow-up of previous abnormal findings",
    "Gastrointestinal symptoms",
    "Diarrhea",
    "Constipation",
    "Blood in stool",
    "Chronic abdominal discomfort",
    "Suspected gastrointestinal bleeding",
    "Suspected diverticular disease",
    "Prior abnormal imaging findings",
    "Abdominal mass on physical examination",
    "Suspected colonic stricture",
    "Screening for Lynch syndrome",
    "Screening for hereditary colon cancer syndromes",
    "Suspected gastrointestinal infection",
    "Chronic inflammatory bowel disease symptoms",
    "Unexplained anemia",
    "Chronic fatigue",
    "Suspected celiac disease",
    "Chronic bloating",
    "Suspected malabsorption syndrome",
    "Suspected Crohn's disease",
    "Suspected ulcerative colitis",
    "Follow-up after gastrointestinal surgery",
    "Recent change in bowel movements",
    "Suspected colonic obstruction",
    "History of gastrointestinal polyps",
    "Persistent gastrointestinal discomfort",
    "Chronic gastritis",
    "History of gastrointestinal bleeding",
    "Unexplained abdominal distension",
    "Screening for colorectal polyps",
    "Monitoring of colonic strictures",
    "History of inflammatory bowel disease",
    "Suspected gastrointestinal motility disorder",
    "Recurrent abdominal pain",
    "Family history of gastrointestinal disorders",
    "Monitoring of gastrointestinal symptoms",
    "Suspected small bowel disease",
    "Chronic nausea",
    "Screening for gastrointestinal malignancies",
    "Evaluation of gastrointestinal symptoms",
    "Chronic vomiting",
    "Suspected rectal prolapse",
    "Evaluation of gastrointestinal bleeding",
    "Monitoring of gastrointestinal inflammation",
    "Chronic indigestion",
    "Suspected malabsorption",
    "Family history of gastrointestinal cancer",
    "Evaluation of persistent gastrointestinal symptoms",
    "Suspected bowel obstruction",
    "Suspected gastrointestinal ulcer",
    "Chronic heartburn",
    "Evaluation of chronic gastrointestinal complaints",
    "Suspected colonic dysmotility",
    "Chronic dysphagia",
    "History of gastrointestinal surgery",
    "Evaluation of chronic diarrhea",
    "Monitoring of gastrointestinal polyps",
    "Suspected bowel ischemia",
    "Suspected gastrointestinal stricture",
    "Evaluation of chronic constipation",
    "Monitoring of gastrointestinal bleeding",
    "Suspected gastrointestinal inflammation",
    "Chronic abdominal cramping",
    "Suspected gastrointestinal malabsorption",
    "History of gastrointestinal infection",
    "Evaluation of chronic abdominal pain",
    "Suspected gastrointestinal dysmotility",
    "Monitoring of gastrointestinal strictures",
    "Suspected gastrointestinal bleeding source",
    "Chronic abdominal discomfort after eating",
    "Evaluation of chronic bloating",
    "Suspected gastrointestinal dysmotility disorder",
    "Chronic diarrhea with weight loss",
    "Evaluation of chronic nausea",
    "Monitoring of gastrointestinal symptoms post-treatment",
    "Suspected gastrointestinal dysmotility syndrome",
    "History of chronic gastrointestinal complaints",
    "Evaluation of chronic vomiting",
    "Monitoring of gastrointestinal symptoms during treatment",
    "Suspected gastrointestinal stricture recurrence",
    "Chronic diarrhea with dehydration",
    "Evaluation of chronic indigestion",
    "Monitoring of gastrointestinal symptoms post-surgery",
    "Suspected gastrointestinal dysmotility disorder recurrence",
    "Chronic abdominal discomfort with meals",
    "Evaluation of chronic dysphagia",
    "Monitoring of gastrointestinal symptoms post-infection",
    "Suspected gastrointestinal stricture persistence",
    "Normal screening colonoscopy",
    "Routine surveillance colonoscopy",
    "No abnormal findings",
    "Negative fecal occult blood test follow-up",
    "No evidence of colorectal pathology"
]
medications_pool = [
    "Midazolam 2 mg IV",
    "Fentanyl 100 micrograms IV",
    "Propofol 50 mg IV",
    "Lidocaine 2% gel",
    "Hydrocortisone 100 mg IV",
    "Diphenhydramine 50 mg IV",
    "Morphine 5 mg IV",
    "Hydromorphone 1 mg IV",
    "Ondansetron 4 mg IV",
    "Ketamine 50 mg IV",
    "Diazepam 5 mg IV",
    "Lorazepam 2 mg IV",
    "Meperidine 50 mg IV",
    "Promethazine 25 mg IV",
    "Dexmedetomidine 0.5 mcg/kg IV",
    "Remifentanil 0.05 mcg/kg/min IV infusion",
    "Propofol 150 mg IV bolus followed by 5-10 mg/kg/min IV infusion",
    "Lidocaine 100 mg IV bolus",
    "Scopolamine 0.4 mg IV",
    "Granisetron 1 mg IV",
    "Haloperidol 5 mg IV",
    "Metoclopramide 10 mg IV",
    "Glycopyrrolate 0.2 mg IV",
    "Atropine 0.5 mg IV",
    "Dexamethasone 8 mg IV",
    "Hydrocortisone 100 mg IV",
    "Methylprednisolone 40 mg IV",
    "Ketorolac 30 mg IV",
    "Acetaminophen 1 g IV",
    "Ibuprofen 800 mg IV",
    "Naproxen 500 mg IV",
    "Aspirin 325 mg IV",
    "Celecoxib 200 mg IV",
    "Tramadol 50 mg IV",
    "Codeine 30 mg IV",
    "Oxycodone 5 mg IV",
    "Loperamide 4 mg IV",
    "Bisacodyl 10 mg rectal suppository",
    "Polyethylene glycol 4 L oral solution",
    "Magnesium citrate 300 mL oral solution",
    "Sodium picosulfate 10 mg oral solution",
    "Docusate sodium 100 mg oral capsule",
    "Sennosides 8.6 mg oral tablet",
    "Lubiprostone 24 mcg oral capsule",
    "Linaclotide 290 mcg oral capsule",
    "Prochlorperazine 10 mg IV",
    "Haloperidol 5 mg IV",
    "Metoclopramide 10 mg IV",
    "Granisetron 1 mg IV",
    "Palonosetron 0.075 mg IV",
    "Droperidol 2.5 mg IV",
    "Fospropofol 100-200 mg IV bolus",
    "Etomidate 0.2-0.6 mg/kg IV bolus",
    "Succinylcholine 1-2 mg/kg IV bolus",
    "Rocuronium 0.6-1.2 mg/kg IV bolus",
    "Vecuronium 0.08-0.1 mg/kg IV bolus",
    "Cisatracurium 0.1-0.2 mg/kg IV bolus",
    "Pancuronium 0.04-0.08 mg/kg IV bolus",
    "Atracurium 0.4-0.5 mg/kg IV bolus",
    "Neostigmine 0.03-0.07 mg/kg IV bolus",
    "Sugammadex 2-4 mg/kg IV bolus",
    "Flumazenil 0.2 mg IV",
    "Naloxone 0.4-2 mg IV",
    "Physostigmine 0.5-2 mg IV",
    "Ephedrine 5-10 mg IV",
    "Phenylephrine 50-200 mcg IV",
    "Epinephrine 0.01-0.1 mg IV",
    "Dopamine 1-5 mcg/kg/min IV infusion",
    "Dobutamine 2-20 mcg/kg/min IV infusion",
    "Nitroglycerin 5-100 mcg/min IV infusion",
    "Isosorbide dinitrate 1-10 mg IV",
    "Verapamil 5-10 mg IV",
    "Diltiazem 10-25 mg IV",
    "Atenolol 5-10 mg IV",
    "Metoprolol 1-5 mg IV",
    "Propranolol 1-3 mg IV",
    "Amiodarone 150 mg IV",
    "Lidocaine 100 mg IV bolus",
    "Bupivacaine 5-10 mg IV bolus",
    "Ropivacaine 5-10 mg IV bolus",
    "Epinephrine 5-10 mcg/mL IV",
    "Tetracaine 0.5-1% IV",
    "Lidocaine-prilocaine cream Apply a thick layer topically to the skin",
    "Clonidine 0.1-0.3 mg IV",
    "Dexlansoprazole 60 mg oral capsule",
    "Esomeprazole 40 mg oral capsule",
    "Lansoprazole 30 mg oral capsule",
    "Omeprazole 20 mg oral capsule",
    "Pantoprazole 40 mg oral tablet",
    "Rabeprazole 20 mg oral tablet",
    "Famotidine 20 mg IV",
    "Ranitidine 50 mg IV",
    "Cimetidine 300 mg IV",
    "Nizatidine 150 mg IV",
    "Sucralfate 1 g oral suspension",
    "Bismuth subsalicylate 525 mg oral tablet",
    "Misoprostol 200 mcg oral tablet",
    "Aprepitant 40 mg oral capsule",
    "Dexamethasone 8 mg IV",
    "Ondansetron 8 mg IV",
    "Prochlorperazine 10 mg IV",
    "Metoclopramide 10 mg IV"
]
complications_pool = [
    "No immediate complications.",
    "Mild abdominal discomfort.",
    "Minor bleeding at the insertion site.",
    "Temporary hypotension.",
    "Mild post-procedure bloating.",
    "Slight nausea after the procedure.",
    "Transient dizziness during recovery.",
    "Temporary headache post-procedure.",
    "Mild gas pains following colonoscopy.",
    "Brief lightheadedness during recovery.",
    "Minor bruising at the injection site.",
    "Temporary increase in heart rate post-procedure.",
    "Mild irritation at the IV site.",
    "Brief episode of low-grade fever.",
    "Temporary soreness in the throat.",
    "Mild cramping during bowel preparation.",
    "Transient discomfort from gas insufflation.",
    "Minor irritation from adhesive tape.",
    "Temporary elevation in blood pressure.",
    "Brief period of post-procedure fatigue.",
    "Mild sensation of bloating.",
    "Temporary numbness at the IV site.",
    "Minor discomfort during scope insertion.",
    "Brief period of light-headedness post-procedure.",
    "Mild irritation of the nasal passages.",
    "Transient flushing or warmth.",
    "Temporary loss of appetite post-procedure.",
    "Mild itching or rash from medical tape.",
    "Brief period of difficulty swallowing.",
    "Temporary metallic taste in the mouth.",
    "Minor irritation or redness at the injection site.",
    "Transient hoarseness or throat irritation.",
    "Mild discomfort from bowel distension.",
    "Brief period of post-procedure shivering.",
    "Temporary difficulty in urination.",
    "Mild post-procedure muscle aches.",
    "Brief period of post-procedure drowsiness.",
    "Transient difficulty in focusing vision.",
    "Temporary tenderness or soreness in the abdomen.",
    "Mild discomfort from scope manipulation.",
    "Brief period of post-procedure anxiety.",
    "Temporary dryness or irritation of the mouth.",
    "Minor irritation or redness at the electrode site.",
    "Transient feeling of fullness in the abdomen.",
    "Mild pain or discomfort during scope withdrawal.",
    "Brief period of post-procedure restlessness.",
    "Temporary stiffness or soreness in the neck.",
    "Mild irritation or redness at the site of adhesive removal.",
    "Transient feeling of weakness or fatigue.",
    "Temporary dryness or irritation of the eyes.",
    "Mild discomfort from residual gas.",
    "Brief period of post-procedure irritability.",
    "Temporary tenderness or soreness in the back.",
    "Mild irritation or redness at the site of oxygen cannula.",
    "Transient feeling of coldness or chills.",
    "Temporary dryness or irritation of the throat.",
    "Mild discomfort from residual scope lubricant.",
    "Brief period of post-procedure nervousness.",
    "Temporary tenderness or soreness in the arm.",
    "Mild irritation or redness at the site of pulse oximeter.",
    "Transient feeling of heat or warmth.",
    "Temporary dryness or irritation of the nasal passages.",
    "Mild discomfort from residual colonoscope.",
    "Brief period of post-procedure sadness or emotional distress.",
    "Temporary tenderness or soreness in the leg.",
    "Mild irritation or redness at the site of blood pressure cuff.",
    "Transient feeling of numbness or tingling.",
    "Temporary dryness or irritation of the skin.",
    "Mild discomfort from residual biopsy forceps.",
    "Brief period of post-procedure confusion.",
    "Temporary tenderness or soreness in the hand.",
    "Mild irritation or redness at the site of ECG electrodes.",
    "Transient feeling of pressure or heaviness.",
    "Temporary dryness or irritation of the lips.",
    "Mild discomfort from residual suction device.",
    "Brief period of post-procedure agitation.",
    "Temporary tenderness or soreness in the foot.",
    "Mild irritation or redness at the site of IV catheter.",
    "Transient feeling of tingling or pins and needles.",
    "Temporary dryness or irritation of the ears.",
    "Mild discomfort from residual air insufflator.",
    "Brief period of post-procedure irritability.",
    "Temporary tenderness or soreness in the shoulder.",
    "Mild irritation or redness at the site of pulse oximeter.",
    "Transient feeling of discomfort or unease.",
    "Temporary dryness or irritation of the mouth.",
    "Mild discomfort from residual bite block.",
    "Brief period of post-procedure restlessness.",
    "Temporary tenderness or soreness in the wrist.",
    "Mild irritation or redness at the site of blood pressure cuff.",
    "Transient feeling of restlessness or agitation.",
    "Temporary dryness or irritation of the throat.",
    "Mild discomfort from residual suction device.",
    "Brief period of post-procedure nervousness.",
    "Temporary tenderness or soreness in the ankle.",
    "Mild irritation or redness at the site of ECG electrodes.",
    "Transient feeling of pressure or tightness.",
    "Temporary dryness or irritation of the skin.",
    "Mild discomfort from residual air insufflator.",
    "Brief period of post-procedure agitation.",
    "Temporary tenderness or soreness in the elbow.",
    "Mild irritation or redness at the site of IV catheter.",
    "Transient feeling of tingling or pins and needles.",
    "Temporary dryness or irritation of the lips."
]
findings_pool = [
    "No significant abnormalities.",
    "Polyp detected in the sigmoid colon.",
    "Diverticula seen in the descending colon.",
    "Mucosal erythema observed in the rectum.",
    "No abnormalities detected.",
    "Normal colonoscopy findings.",
    "No significant findings noted.",
    "Colonoscopy findings within normal limits.",
    "No findings requiring further intervention.",
    "Routine colonoscopy results, no concerns.",
    "No abnormalities identified.",
    "No significant pathology detected.",
    "Normal post-procedure findings.",
    "Colonoscopy results negative for abnormalities.",
    "No abnormalities warranting additional follow-up.",
    "Routine post-procedure findings observed.",
    "Colonoscopy findings consistent with expectations.",
    "No evidence of abnormality.",
    "No concerning findings identified.",
    "No abnormalities necessitating further investigation.",
    "Normal colonoscopy, no further action needed.",
    "No significant pathology found.",
    "Colonoscopy results reassuring, no issues.",
    "No significant findings requiring intervention.",
    "Routine post-procedure recovery observed.",
    "No significant abnormalities seen.",
    "Colonoscopy results benign, no pathology identified.",
    "No abnormalities warranting further evaluation.",
    "Colonoscopy performed without incident.",
    "No significant findings during the procedure.",
    "No abnormalities detected on colonoscopic examination.",
    "Routine post-procedure course observed.",
    "No significant complications encountered.",
    "Colonoscopy findings unremarkable, no concerns.",
    "No significant pathology identified.",
    "Routine colonoscopy results, no abnormalities detected.",
    "No significant findings warranting additional investigation.",
    "Colonoscopy performed as expected, no complications.",
    "No abnormalities noted on post-procedure assessment.",
    "Routine post-procedure recovery, no complications.",
    "Colonoscopy findings negative for abnormalities.",
    "No significant findings during the examination.",
    "Routine colonoscopy results, no complications.",
    "No significant abnormalities requiring further action.",
    "Colonoscopy results normal, no concerning findings.",
    "No significant findings requiring further evaluation.",
    "Routine post-procedure course, no complications.",
    "Colonoscopy performed safely without complications.",
    "No significant pathology requiring further investigation.",
    "Routine post-procedure recovery, no issues.",
    "Colonoscopy results within expected range.",
    "No significant complications observed.",
    "Routine colonoscopy results, no further action required.",
    "Colonoscopy findings unremarkable, no abnormalities.",
    "No significant findings noted during the exam.",
    "Routine post-procedure recovery, no adverse effects.",
    "Colonoscopy performed as planned, no complications.",
    "No significant findings requiring additional follow-up.",
    "Routine colonoscopy results, no concerns.",
    "Colonoscopy findings normal, no significant pathology detected.",
    "No significant abnormalities found on colonoscopy.",
    "Routine post-procedure recovery, no complications observed.",
    "Colonoscopy performed safely, no adverse outcomes.",
    "No significant pathology detected on colonoscopy.",
    "Routine colonoscopy results, no abnormalities.",
    "No significant findings warranting extended observation.",
    "Colonoscopy results negative, no pathology identified.",
    "Routine post-procedure recovery, no issues reported.",
    "Colonoscopy findings unremarkable, no abnormalities detected.",
    "No significant abnormalities warranting further intervention.",
    "Colonoscopy performed without adverse events.",
    "Routine post-procedure recovery, no complications encountered.",
    "Colonoscopy results normal, no abnormalities identified.",
    "No significant findings requiring additional investigation.",
    "Routine colonoscopy results, no complications reported.",
    "Colonoscopy findings consistent with previous exams.",
    "No significant findings identified during post-procedure evaluation.",
    "Routine post-procedure recovery, no complications observed.",
    "Colonoscopy performed safely, no complications encountered.",
    "No significant abnormalities detected on post-procedure assessment.",
    "Routine colonoscopy results, no significant findings.",
    "Colonoscopy findings negative, no concerning abnormalities.",
    "No significant complications observed during post-procedure assessment.",
    "Routine colonoscopy results, no abnormalities detected.",
    "No significant abnormalities noted on post-procedure assessment.",
    "Colonoscopy performed without incident, no complications.",
    "No significant findings warranting further investigation.",
    "Routine post-procedure recovery, no complications encountered.",
    "Colonoscopy findings normal, no significant pathology detected.",
    "No significant findings requiring further intervention.",
    "Routine colonoscopy results, no complications.",
    "Colonoscopy results negative, no concerning findings.",
    "No significant findings observed during post-procedure assessment.",
    "Routine colonoscopy results, no abnormalities detected.",
    "Colonoscopy findings unremarkable, no significant abnormalities detected."
    "Inflammation present in the ascending colon.",
    "Ulceration observed in the rectum.",
    "Mass detected in the descending colon.",
    "Bleeding source identified in the sigmoid colon.",
    "Hemorrhoids observed in the rectum.",
    "Abnormal tissue growth seen in the cecum.",
    "Narrowing of the colon noted in the transverse colon.",
    "Fecal impaction found in the sigmoid colon.",
    "Perforation suspected in the ascending colon.",
    "Excessive mucus observed in the descending colon.",
    "Infection suspected in the rectum.",
    "Foreign body detected in the ascending colon.",
    "Inflammatory polyp found in the sigmoid colon.",
    "Stricture noted in the rectum.",
    "Adenomatous polyp detected in the descending colon.",
    "Pseudopolyp seen in the ascending colon.",
    "Fistula suspected in the sigmoid colon.",
    "Erythematous mucosa observed in the rectum.",
    "Vascular malformation found in the descending colon.",
    "Protruding lesion seen in the ascending colon."
]
impression_pool = [
    "No significant abnormalities detected.",
    "Further evaluation recommended for detected polyp.",
    "Mild inflammation noted, likely due to diverticulosis.",
    "Normal colonoscopy findings, no further action required.",
    "Impression consistent with routine colonoscopic examination.",
    "No concerning pathology identified, follow-up not necessary.",
    "Benign findings observed, no need for additional intervention.",
    "Colonoscopy results negative for significant abnormalities.",
    "No evidence of malignancy detected, routine surveillance recommended.",
    "Polyp removed and submitted for histopathological examination.",
    "Findings consistent with previous colonoscopic evaluations.",
    "No pathology requiring immediate attention identified.",
    "Colonoscopy results reassuring, no further action needed.",
    "Impression consistent with expected post-procedure course.",
    "No suspicious lesions seen, regular screening advised.",
    "No acute abnormalities detected, continue with standard care.",
    "Normal post-procedure impression, no complications identified.",
    "Biopsy specimens obtained for further analysis.",
    "Follow-up colonoscopy recommended based on clinical findings.",
    "Polyp resected completely, no residual tissue observed.",
    "Colonoscopic findings stable compared to prior examinations.",
    "Impression benign, no evidence of advanced neoplasia.",
    "No significant changes compared to previous colonoscopy.",
    "Biopsies taken from suspicious areas for pathological assessment.",
    "Colonoscopy results consistent with pre-procedure expectations.",
    "No concerning features identified, ongoing surveillance advised.",
    "Impression unremarkable, no need for immediate intervention.",
    "Colonoscopy findings in line with patient's clinical history.",
    "No evidence of dysplasia or carcinoma detected.",
    "Polyps removed successfully, no residual lesions identified.",
    "No acute abnormalities seen, continue with standard follow-up.",
    "Impression normal, no pathology requiring further investigation.",
    "Colonoscopy results negative for high-risk lesions.",
    "No concerning features noted, plan for routine follow-up.",
    "Tissue samples collected for histological analysis.",
    "Findings consistent with benign colorectal polyps.",
    "No signs of acute inflammation or infection observed.",
    "Colonoscopy results within expected range, no additional action necessary.",
    "No evidence of inflammatory bowel disease detected.",
    "Impression unchanged from prior examinations, no new pathology identified.",
    "Polypoid lesions excised completely, no residual tissue present.",
    "No evidence of dysplasia or malignancy, continue with regular surveillance.",
    "Normal post-procedure impression, patient can resume normal activities.",
    "No features suggestive of advanced neoplasia seen.",
    "Colonoscopy findings stable, no progression of known pathology.",
    "No evidence of ischemia or vascular abnormalities detected.",
    "Impression benign, no indication of significant pathology.",
    "Colonoscopy results consistent with patient's clinical presentation.",
    "No concerning lesions identified, plan for routine monitoring.",
    "No need for immediate intervention, continue with standard care.",
    "Impression normal, no pathology requiring urgent attention.",
    "Colonoscopy findings unremarkable, no evidence of disease progression.",
    "No features concerning for malignancy detected.",
    "Polyps removed with clear margins, no residual adenomatous tissue.",
    "No signs of acute complications following the procedure.",
    "Impression consistent with benign colorectal changes.",
    "Colonoscopy results negative for advanced neoplasia.",
    "No evidence of active bleeding or vascular abnormalities seen.",
    "Findings consistent with benign mucosal changes.",
    "No significant deviations from expected findings, no further action needed.",
    "Polyps removed successfully, no complications encountered.",
    "No concerning features noted, continue with regular monitoring.",
    "Tissue samples sent for pathological examination.",
    "Colonoscopy results within normal limits, no worrisome findings detected.",
    "No evidence of malignancy or dysplasia, continue with routine surveillance.",
    "Normal post-procedure impression, patient discharged home.",
    "No significant pathology identified, routine follow-up recommended.",
    "Impression unchanged from previous exams, no new concerns.",
    "Colonoscopy findings stable, no evidence of disease recurrence.",
    "No features suggestive of infectious colitis or other acute pathology.",
    "Impression benign, no indication of significant mucosal abnormalities.",
    "Colonoscopy results consistent with expected post-procedure course.",
    "No concerning lesions identified, patient advised to continue regular care.",
    "No need for immediate intervention, plan for routine follow-up.",
    "Impression normal, no evidence of significant colonic disease.",
    "Colonoscopy findings unremarkable, no new abnormalities detected.",
    "No features concerning for high-grade dysplasia or malignancy.",
    "Polyps removed completely, no residual adenomas visualized.",
    "No signs of procedural complications observed.",
    "Impression consistent with benign colorectal findings.",
    "Colonoscopy results negative for significant pathology.",
    "No evidence of active inflammation or other acute abnormalities seen.",
    "Findings consistent with normal colonic mucosa.",
    "No significant deviations from expected findings, no further intervention required.",
    "Polyps removed successfully, no complications encountered during the procedure.",
    "No concerning features noted, patient advised to maintain regular follow-up appointments.",
    "Tissue samples obtained for pathological assessment, results pending.",
    "Colonoscopy results within expected range, no significant abnormalities detected.",
    "No evidence of dysplasia or malignancy, patient advised to continue surveillance as scheduled."
]
recommendations_pool = [
    "Follow up with gastroenterologist for further evaluation.",
    "Repeat colonoscopy in 5 years for surveillance.",
    "Commence treatment for detected condition.",
    "No further action needed, resume regular activities.",
    "Continue with current management plan.",
    "Schedule follow-up appointment with primary care physician.",
    "Educate patient on colorectal cancer screening options.",
    "Advise lifestyle modifications to improve colon health.",
    "No specific recommendations at this time.",
    "Refer patient to colorectal surgeon for specialized care.",
    "Monitor symptoms closely and report any changes.",
    "Discuss screening options with family members.",
    "Encourage regular exercise and healthy diet.",
    "Provide patient education materials on colon health.",
    "Recommend genetic counseling for familial conditions.",
    "Suggest dietary changes to alleviate gastrointestinal symptoms.",
    "Refer to nutritionist for dietary counseling.",
    "Monitor for signs of gastrointestinal bleeding.",
    "Educate patient on importance of regular screenings.",
    "Encourage smoking cessation to reduce colorectal cancer risk.",
    "Discuss benefits of regular fiber intake for colon health.",
    "Schedule follow-up appointment for medication review.",
    "Refer to gastroenterology clinic for specialized care.",
    "Monitor for signs of infection and report any concerns.",
    "Advise on importance of maintaining a healthy weight.",
    "Discuss alcohol moderation for gastrointestinal health.",
    "Provide resources for managing gastrointestinal symptoms.",
    "Encourage adherence to prescribed medications.",
    "Refer to mental health professional for coping strategies.",
    "Discuss options for managing chronic gastrointestinal conditions.",
    "Schedule follow-up appointment for symptom review.",
    "Educate patient on signs and symptoms of colorectal cancer.",
    "Encourage regular hydration for colon health.",
    "Refer to support groups for patients with similar conditions.",
    "Advise on importance of stress management for gastrointestinal health.",
    "Provide information on available clinical trials.",
    "Discuss potential benefits of probiotics for gut health.",
    "Refer for further evaluation of abnormal laboratory results.",
    "Recommend regular screening for other gastrointestinal conditions.",
    "Encourage participation in colorectal cancer awareness events.",
    "Provide resources for managing gastrointestinal side effects of medications.",
    "Refer to physical therapist for exercises to improve bowel function.",
    "Suggest mindfulness techniques for symptom management.",
    "Educate patient on importance of regular sleep patterns for gut health.",
    "Refer for evaluation of possible food intolerances or allergies.",
    "Encourage participation in regular physical activity.",
    "Discuss options for managing gastrointestinal reflux symptoms.",
    "Provide information on relaxation techniques for symptom relief.",
    "Refer to colorectal cancer survivor support groups.",
    "Encourage regular consumption of fruits and vegetables.",
    "Schedule follow-up appointment for monitoring of condition.",
    "Educate patient on potential side effects of medications.",
    "Refer for evaluation of possible gastrointestinal motility disorders.",
    "Suggest strategies for managing irritable bowel syndrome symptoms.",
    "Discuss potential benefits of mindfulness-based stress reduction for symptom relief.",
    "Provide resources for managing gastrointestinal symptoms during travel.",
    "Encourage regular consumption of whole grains for colon health.",
    "Refer to specialist for further evaluation of complex gastrointestinal conditions.",
    "Suggest dietary modifications to alleviate gas and bloating.",
    "Discuss options for managing chronic constipation.",
    "Provide information on available community resources for patients with gastrointestinal conditions.",
    "Refer for evaluation of possible gastrointestinal infections.",
    "Encourage regular screening for other gastrointestinal cancers.",
    "Discuss options for managing inflammatory bowel disease symptoms.",
    "Suggest strategies for managing gastrointestinal discomfort during menstruation.",
    "Educate patient on potential benefits of regular physical activity for colon health.",
    "Provide resources for managing gastrointestinal symptoms during pregnancy.",
    "Refer for evaluation of possible lactose intolerance.",
    "Suggest strategies for managing gastrointestinal symptoms during menopause.",
    "Encourage regular consumption of fermented foods for gut health.",
    "Refer to specialist for further evaluation of persistent symptoms.",
    "Discuss options for managing chronic diarrhea.",
    "Provide information on available online support groups for patients with gastrointestinal conditions.",
    "Refer for evaluation of possible celiac disease.",
    "Suggest strategies for managing gastrointestinal symptoms during chemotherapy.",
    "Educate patient on potential benefits of regular meditation for gut health.",
    "Encourage regular consumption of prebiotic foods for colon health.",
    "Refer for evaluation of possible gastrointestinal bleeding.",
    "Discuss options for managing gastroesophageal reflux disease symptoms.",
    "Provide resources for managing gastrointestinal symptoms during chemotherapy.",
    "Refer to specialist for further evaluation of complex gastrointestinal symptoms.",
    "Suggest strategies for managing gastrointestinal symptoms during radiation therapy.",
    "Encourage regular consumption of probiotic-rich foods for gut health.",
    "Refer for evaluation of possible gluten sensitivity.",
    "Discuss options for managing functional gastrointestinal disorders.",
    "Provide information on available telemedicine services for patients with gastrointestinal conditions.",
    "Refer for evaluation of possible pancreatic insufficiency.",
    "Suggest strategies for managing gastrointestinal symptoms during immunosuppressive therapy.",
    "Educate patient on potential benefits of regular yoga practice for gut health.",
    "Encourage regular consumption of high-fiber foods for colon health.",
    "Refer for evaluation of possible small intestinal bacterial overgrowth.",
    "Discuss options for managing gastrointestinal symptoms during hormone therapy.",
    "Provide resources for managing gastrointestinal symptoms during dialysis.",
    "Refer to specialist for further evaluation of recurrent symptoms."
]
cpt_procedure_codes_pool = [
    "45378: Colonoscopy, flexible, diagnostic",
    "45380: Colonoscopy with removal of tumor(s)",
    "45385: Colonoscopy, flexible; with removal of tumor(s), polyp(s), or other lesion(s) by snare technique",
    "45378-59: Colonoscopy, flexible, diagnostic (modifier indicating distinct procedural service)",
    "45379: Colonoscopy, flexible, with directed submucosal injection(s), any substance",
    "45380-59: Colonoscopy, flexible; with biopsy, single or multiple (modifier indicating distinct procedural service)",
    "45381: Colonoscopy, flexible; with directed submucosal injection(s), any substance",
    "45384: Colonoscopy, flexible; with ablation of tumor(s), polyp(s), or other lesion(s) not amenable to removal by hot biopsy forceps, bipolar cautery or snare technique",
    "45388: Colonoscopy through stoma; diagnostic, with or without collection of specimen(s) by brushing or washing, with or without colon decompression (separate procedure)",
    "45390: Colonoscopy through stoma; with removal of tumor(s), polyp(s), or other lesion(s), with or without collection of specimen(s) by brushing or washing, with or without colon decompression (separate procedure)",
    "45391: Colonoscopy through stoma; with directed submucosal injection(s), any substance, with or without collection of specimen(s) by brushing or washing, with or without colon decompression (separate procedure)",
    "45392: Colonoscopy through stoma; with control of hemorrhage, with or without collection of specimen(s) by brushing or washing, with or without colon decompression (separate procedure)",
    "45393: Colonoscopy through stoma; with ablation of tumor(s), polyp(s), or other lesion(s), not amenable to removal by hot biopsy forceps, bipolar cautery or snare technique, with or without collection of specimen(s) by brushing or washing, with or without colon decompression (separate procedure)",
    "45398: Unlisted procedure, colon",
    "G0105: Colorectal cancer screening; colonoscopy on individual at high risk",
    "G0121: Colorectal cancer screening; colonoscopy on individual not meeting criteria for high risk",
    "G0106: Colorectal cancer screening; alternative to G0105, screening sigmoidoscopy, barium enema",
    "G0107: Colorectal cancer screening; colonoscopy on individual at high risk; alternate to G0121",
    "G0108: Colorectal cancer screening; fecal occult blood test, immunoassay, 1-3 simultaneous",
    "G0109: Colorectal cancer screening; fecal occult blood test, immunoassay, for colorectal neoplasm, interpreted by physician",
    "G0111: Colorectal cancer screening; colonoscopy on individual not meeting criteria for high risk; alternate to G0106",
    "G0120: Colorectal cancer screening; alternative to G0105, screening sigmoidoscopy, barium enema",
    "G0122: Colorectal cancer screening; alternative to G0121, screening sigmoidoscopy, barium enema",
    "G0123: Colorectal cancer screening; alternative to G0106, screening sigmoidoscopy, barium enema",
    "G0124: Colorectal cancer screening; alternative to G0121, screening sigmoidoscopy, barium enema",
    "G0125: Colorectal cancer screening; alternative to G0105, screening sigmoidoscopy, barium enema",
    "G0126: Colorectal cancer screening; alternative to G0121, screening sigmoidoscopy, barium enema",
    "G0127: Colorectal cancer screening; alternative to G0106, screening sigmoidoscopy, barium enema",
    "G0128: Colorectal cancer screening; alternative to G0121, screening sigmoidoscopy, barium enema"
]
icd_diagnosis_codes_pool = [
    "K63.0: Abscess of intestine",
    "K63.3: Fistula of intestine",
    "K63.4: Enteroptosis",
    "K63.89: Other specified diseases of intestine",
    "K92.2: Gastrointestinal hemorrhage, other",
    "K92.9: Gastrointestinal hemorrhage, unspecified",
    "K57.90: Diverticulosis of intestine, part unspecified, without perforation or abscess without bleeding",
    "K57.32: Diverticulitis of large intestine without perforation or abscess without bleeding",
    "K51.919: Ulcerative colitis, unspecified with unspecified complications",
    "K50.919: Crohn's disease, unspecified with unspecified complications",
    "K52.89: Other specified noninfective gastroenteritis and colitis",
    "K63.2: Rectal fistula",
    "K63.3: Anal fistula",
    "K63.89: Other specified diseases of intestine",
    "K92.9: Gastrointestinal hemorrhage, unspecified",
    "K92.9: Gastrointestinal hemorrhage, unspecified",
    "R19.5: Other fecal abnormalities",
    "R19.6: Hyperperistalsis",
    "R19.3: Abdominal rigidity",
    "R19.2: Abdominal tenderness",
    "R19.1: Intra-abdominal and pelvic swelling, mass, or lump",
    "R19.0: Intra-abdominal and pelvic swelling, mass, or lump",
    "R19.11: Right upper quadrant abdominal swelling, mass, or lump",
    "R19.12: Left upper quadrant abdominal swelling, mass, or lump",
    "R19.13: Epigastric abdominal swelling, mass, or lump",
    "R19.14: Hypochondriac abdominal swelling, mass, or lump",
    "R19.15: Right lower quadrant abdominal swelling, mass, or lump",
    "R19.16: Left lower quadrant abdominal swelling, mass, or lump",
    "R19.17: Periumbilic abdominal swelling, mass, or lump",
    "R19.18: Other abdominal swelling, mass, or lump",
    "R19.19: Unspecified abdominal swelling, mass, or lump",
    "R19.21: Right upper quadrant abdominal tenderness",
    "R19.22: Left upper quadrant abdominal tenderness",
    "R19.23: Epigastric abdominal tenderness",
    "R19.24: Hypochondriac abdominal tenderness",
    "R19.25: Right lower quadrant abdominal tenderness",
    "R19.26: Left lower quadrant abdominal tenderness",
    "R19.27: Periumbilic abdominal tenderness",
    "R19.28: Other abdominal tenderness",
    "R19.29: Unspecified abdominal tenderness"
]
attending_participation_pool = [
    "The procedure was performed by Dr. Smith.",
    "Dr. Johnson assisted in the procedure.",
    "Dr. Martinez oversaw the procedure.",
    "Dr. Brown conducted the colonoscopy.",
    "Dr. Wilson supervised the examination.",
    "Dr. Garcia led the colonoscopy.",
    "Dr. Taylor provided guidance during the procedure.",
    "Dr. Lee was present throughout the examination.",
    "Dr. Anderson assisted in the colonoscopy.",
    "Dr. Perez conducted the procedure successfully.",
    "Dr. Thomas performed the colonoscopy with expertise.",
    "Dr. Hall monitored the patient's condition closely.",
    "Dr. Clark ensured the procedure went smoothly.",
    "Dr. Rodriguez led the team during the colonoscopy.",
    "Dr. Lewis provided necessary assistance during the examination.",
    "Dr. Walker oversaw the entire procedure.",
    "Dr. White conducted the colonoscopy professionally.",
    "Dr. Harris assisted Dr. Smith during the procedure.",
    "Dr. Martin collaborated with Dr. Johnson throughout the examination.",
    "Dr. King ensured patient safety during the colonoscopy.",
    "Dr. Baker supervised the endoscopy procedure.",
    "Dr. Perez guided the scope carefully through the colon.",
    "Dr. Cooper provided support to the medical team.",
    "Dr. Hughes monitored vital signs throughout the examination.",
    "Dr. Flores assisted in navigating the colonoscope.",
    "Dr. Richardson conducted the procedure efficiently.",
    "Dr. Wood oversaw the entire process.",
    "Dr. Brooks ensured patient comfort during the colonoscopy.",
    "Dr. Watson provided expertise in gastroenterology.",
    "Dr. Sanchez assisted in the examination process.",
    "Dr. Hill supervised the insertion and withdrawal of the scope.",
    "Dr. Long performed the colonoscopy with precision.",
    "Dr. Russell monitored the patient's response to sedation.",
    "Dr. Diaz guided the scope through the colon meticulously.",
    "Dr. Nguyen provided necessary assistance to Dr. Martinez.",
    "Dr. Carter ensured the colonoscopy was completed thoroughly.",
    "Dr. Reyes conducted the examination with care.",
    "Dr. Patel supervised the medical team throughout the procedure.",
    "Dr. Rivera assisted in maintaining patient comfort.",
    "Dr. Stewart conducted the colonoscopy successfully.",
    "Dr. Morris provided guidance on next steps after the examination.",
    "Dr. Rogers assisted in handling any complications that arose.",
    "Dr. Gray ensured the procedure adhered to safety protocols.",
    "Dr. James oversaw the entire endoscopic process.",
    "Dr. Coleman assisted in obtaining biopsy samples.",
    "Dr. Green provided expertise in interpreting findings.",
    "Dr. Reed monitored for any signs of adverse reactions.",
    "Dr. Price ensured the procedure was conducted efficiently.",
    "Dr. Bell assisted in the navigation of the colonoscope.",
    "Dr. Bailey provided support to the nursing staff.",
    "Dr. Cooper ensured patient privacy and dignity throughout the procedure.",
    "Dr. Howard conducted the examination thoroughly.",
    "Dr. Murphy provided expertise in gastrointestinal disorders.",
    "Dr. Peterson assisted in preparing the patient for the colonoscopy.",
    "Dr. Jenkins ensured all necessary equipment was readily available.",
    "Dr. Kelly monitored for any signs of perforation or bleeding.",
    "Dr. Bryant supervised the administration of sedation.",
    "Dr. Griffin provided guidance on post-procedure care.",
    "Dr. Torres assisted in positioning the patient for the examination.",
    "Dr. Ward ensured the procedure room was properly set up.",
    "Dr. Brooks provided expertise in managing inflammatory bowel diseases.",
    "Dr. Butler conducted the colonoscopy with attention to detail.",
    "Dr. Alexander ensured the medical team followed proper infection control measures.",
    "Dr. Barnes assisted in documenting findings during the procedure.",
    "Dr. Fisher provided support to the anesthesia team.",
    "Dr. Henderson supervised the administration of medications.",
    "Dr. Howard ensured the patient understood the procedure and provided informed consent.",
    "Dr. Jenkins assisted in communicating with the patient throughout the examination.",
    "Dr. Kelly provided expertise in managing gastrointestinal bleeding.",
    "Dr. Bryant ensured proper documentation of the procedure.",
    "Dr. Griffin collaborated with the pathology department for timely analysis of biopsy samples.",
    "Dr. Torres provided assistance in maneuvering the scope through the colon.",
    "Dr. Ward ensured the procedure adhered to quality assurance standards.",
    "Dr. Brooks supervised the insertion and withdrawal of the colonoscope.",
    "Dr. Butler provided expertise in identifying and removing polyps.",
    "Dr. Alexander ensured adequate preparation of the colon prior to the procedure.",
    "Dr. Barnes assisted in providing post-procedure instructions to the patient.",
    "Dr. Fisher ensured proper disposal of medical waste after the procedure.",
    "Dr. Henderson supervised the cleaning and sterilization of endoscopic equipment.",
    "Dr. Howard reviewed the findings of the colonoscopy with the patient.",
    "Dr. Jenkins collaborated with radiology for additional imaging if needed.",
    "Dr. Kelly ensured the patient received appropriate follow-up care.",
    "Dr. Bryant provided expertise in managing complications that arose during the procedure.",
    "Dr. Griffin assisted in coordinating care with other healthcare providers.",
    "Dr. Torres ensured the patient's medical records were accurately updated.",
    "Dr. Ward provided guidance on dietary and lifestyle changes post-procedure.",
    "Dr. Brooks collaborated with the patient's primary care physician for ongoing management.",
    "Dr. Butler ensured continuity of care by scheduling follow-up appointments as needed."
]
procedure_intro_pool = [
    "Prior to the procedure, a History and Physical was performed, and patient medications and allergies were reviewed. Informed consent was obtained.",
    "Patient was prepped according to standard protocol, and vital signs were monitored throughout the procedure.",
    "The patient was positioned appropriately, and conscious sedation was administered as per protocol.",
    "The procedure started on time without any delays.",
    "The patient was cooperative and comfortable throughout the examination.",
    "Nursing staff assisted in preparing the patient for the colonoscopy.",
    "The procedure room was properly set up with all necessary equipment.",
    "Anesthesia team ensured the patient was adequately sedated for the procedure.",
    "The endoscope was carefully inserted through the anus and advanced into the colon.",
    "Visualization of the colon was clear, allowing for thorough examination of the mucosa.",
    "The scope was advanced to the cecum with ease.",
    "Adequate insufflation was maintained throughout the procedure.",
    "The entire colon was examined up to the splenic flexure.",
    "Patient tolerated the procedure well without any discomfort.",
    "No adverse events or complications occurred during the examination.",
    "Polyps, if present, were identified and documented.",
    "Biopsy samples were obtained as necessary for further evaluation.",
    "Any bleeding encountered during the procedure was controlled effectively.",
    "The scope was carefully withdrawn while inspecting the colonic mucosa.",
    "Thorough washing of the scope was performed during withdrawal to ensure clear visualization.",
    "The examination was completed in a timely manner.",
    "Patient was monitored in the recovery area following the procedure.",
    "Post-procedure instructions were provided to the patient and/or caregiver.",
    "Patient was discharged home in stable condition.",
    "No immediate complications were observed post-procedure.",
    "The colonoscopy findings were discussed with the patient and documented in the medical record.",
    "Pathology specimens were sent for analysis as indicated.",
    "The patient was scheduled for follow-up as per clinical guidelines.",
    "The procedure was well-tolerated with minimal discomfort.",
    "Patient's vital signs remained stable throughout the examination.",
    "The scope was maneuvered carefully to avoid any trauma to the colonic wall.",
    "Endoscopic landmarks were identified and documented during the examination.",
    "The colonoscopy images were of high quality, allowing for accurate assessment.",
    "Scope withdrawal was performed slowly and meticulously to ensure thorough inspection.",
    "No evidence of perforation or other serious complications was noted.",
    "Patient was monitored closely for any signs of adverse reactions to sedation.",
    "Colon cleanliness was adequate for visualization of the mucosa.",
    "The procedure team communicated effectively throughout the examination.",
    "Any findings of clinical significance were communicated to the patient and/or family.",
    "Proper documentation of the procedure was completed in the medical record.",
    "The patient's comfort and privacy were respected throughout the colonoscopy.",
    "Endoscopic equipment was properly maintained and sterilized prior to use.",
    "Any discrepancies or concerns regarding the procedure were addressed promptly.",
    "The colonoscopy was performed in accordance with established guidelines and protocols.",
    "The procedure was performed by experienced and skilled medical personnel.",
    "Any complications encountered during the procedure were managed promptly and effectively.",
    "Patient's medical history and comorbidities were taken into consideration during the examination.",
    "The procedure team worked collaboratively to ensure the patient's safety and well-being.",
    "Patient was provided with information about the colonoscopy procedure and its risks and benefits.",
    "Scope insertion and withdrawal were performed smoothly and without difficulty.",
    "The colonoscopy findings were discussed with the patient's primary care physician for ongoing management.",
    "Patient's dietary and medication instructions were reviewed prior to the procedure.",
    "Any concerns or questions raised by the patient were addressed satisfactorily.",
    "Patient's anesthesia needs were assessed and addressed appropriately prior to the procedure.",
    "The procedure team followed infection control protocols to minimize the risk of transmission.",
    "Patient was positioned in a comfortable and safe manner for the examination.",
    "All necessary equipment and supplies were readily available for the procedure.",
    "Patient's clinical status was monitored closely throughout the examination.",
    "The endoscope was carefully navigated through the colon to ensure thorough visualization.",
    "Colonoscopy findings were documented accurately in the procedure report.",
    "The procedure team remained vigilant for any signs of procedural complications.",
    "Patient's comfort and well-being were prioritized throughout the examination.",
    "The scope was advanced and withdrawn gently to minimize patient discomfort.",
    "Patient was informed about the potential risks and benefits of the colonoscopy procedure.",
    "The examination room was maintained at an appropriate temperature and lighting level.",
    "The procedure team communicated effectively with the patient and/or family members.",
    "Any findings requiring follow-up were communicated to the patient's healthcare provider.",
    "The colonoscopy procedure was completed within the expected timeframe.",
    "Patient's medical history and relevant clinical information were reviewed prior to the procedure.",
    "Scope withdrawal was performed systematically to ensure all areas of the colon were visualized.",
    "The procedure team remained attentive to the patient's needs and concerns throughout the examination.",
    "Any equipment malfunctions or technical issues were addressed promptly by the procedure team.",
    "Patient's comfort level and sedation status were monitored continuously throughout the examination.",
    "The colonoscopy findings were discussed with the patient's gastroenterologist for further evaluation and management.",
    "Patient's allergies and sensitivities were reviewed prior to administration of any medications.",
    "Colon preparation was thorough and adequate for visualization of the colonic mucosa.",
    "The procedure team maintained a sterile field to minimize the risk of infection.",
    "Any findings requiring intervention or additional testing were communicated to the patient's healthcare provider.",
    "Patient's recovery from sedation was monitored closely in the post-anesthesia care unit.",
    "The procedure team remained attentive to any changes in the patient's clinical status during the examination.",
    "Patient's vital signs were monitored closely throughout the recovery period.",
    "The colonoscopy procedure was performed using the latest endoscopic technology and techniques.",
    "Any complications or adverse events encountered during the procedure were documented in the medical record.",
    "Patient's comfort and safety were the primary concerns throughout the colonoscopy procedure.",
    "The procedure team followed established protocols for the administration of sedation and analgesia.",
    "Scope insertion and withdrawal were performed smoothly and without difficulty.",
    "Patient's level of consciousness and responsiveness were monitored continuously throughout the procedure.",
    "The colonoscopy findings were discussed with the patient's family members, if desired.",
    "The procedure team remained vigilant for any signs of procedural complications.",
    "Patient's post-procedure instructions were reviewed and reinforced prior to discharge.",
    "The colonoscopy procedure was performed in a timely and efficient manner.",
    "Any findings requiring follow-up or further evaluation were communicated to the patient's healthcare provider."
]
procedure_success_pool = [
    "Colonoscope insertion to the cecum was successful.",
    "The colonoscope advanced smoothly through the entire colon.",
    "The procedure progressed without any technical difficulties.",
    "Full examination of the colon was achieved without complications.",
    "Visualization of the colonic mucosa was clear and adequate.",
    "Scope withdrawal was performed systematically with no issues.",
    "No abnormalities were detected during the colonoscopy.",
    "The scope was navigated to the cecum without difficulty.",
    "Colon cleanliness was optimal for visualization of the mucosa.",
    "Biopsy samples were obtained successfully as needed.",
    "Polyps, if present, were identified and removed appropriately.",
    "No evidence of bleeding or other complications was observed.",
    "The patient tolerated the procedure well without discomfort.",
    "All planned interventions were completed successfully.",
    "The procedure was completed within the expected timeframe.",
    "No further action is required based on the colonoscopy findings.",
    "The scope was withdrawn smoothly without causing trauma.",
    "The colonoscope was maneuvered with precision throughout the examination.",
    "Clear images of the colon were obtained during the procedure.",
    "The examination provided a comprehensive assessment of the colonic mucosa.",
    "Patient's vital signs remained stable throughout the examination.",
    "No signs of perforation or other serious complications were noted.",
    "The patient's clinical status remained stable post-procedure.",
    "The colonoscopy findings were consistent with a normal examination.",
    "No abnormalities or lesions requiring intervention were identified.",
    "Patient's recovery from sedation was uneventful.",
    "The colonoscopy procedure was deemed successful and complete.",
    "All areas of the colon were visualized thoroughly during the examination.",
    "Scope withdrawal was performed gently to minimize patient discomfort.",
    "Patient was discharged home in good condition after the procedure.",
    "No adverse events occurred during or after the colonoscopy.",
    "The procedure team worked efficiently and effectively throughout the examination.",
    "Colon preparation was excellent, allowing for optimal visualization.",
    "Patient's sedation level was appropriate for the procedure.",
    "The scope was advanced and withdrawn without difficulty or resistance.",
    "The colonoscopy findings were consistent with the patient's clinical history.",
    "No abnormal findings were detected that require further investigation.",
    "The examination provided valuable diagnostic information.",
    "Patient's comfort and safety were maintained throughout the procedure.",
    "No complications occurred that necessitated additional interventions.",
    "The colonoscopy procedure was completed without incident.",
    "The patient's clinical status remained unchanged post-procedure.",
    "No adverse reactions to sedation were observed.",
    "The colonoscopy results were discussed with the patient and documented.",
    "The examination was performed according to established protocols and guidelines.",
    "Patient's medical records were updated with the colonoscopy findings.",
    "The procedure team communicated effectively throughout the examination.",
    "Patient's questions and concerns were addressed satisfactorily.",
    "No evidence of inflammation or other pathological changes was noted.",
    "The colonoscopy was deemed successful, and no further action is needed.",
    "The examination provided reassurance regarding the patient's gastrointestinal health.",
    "No abnormalities requiring immediate attention were identified.",
    "Patient's recovery from sedation proceeded smoothly without complications.",
    "The procedure room was left in a clean and orderly condition.",
    "The colonoscopy findings were communicated to the patient's healthcare provider.",
    "No adverse effects of sedation were reported post-procedure.",
    "Patient was informed of the colonoscopy results and provided with appropriate follow-up instructions.",
    "The procedure team ensured patient privacy and dignity throughout the examination.",
    "Colonoscope insertion and withdrawal were performed with minimal discomfort to the patient.",
    "The colonoscopy results were consistent with a normal examination.",
    "Patient's clinical condition remained stable throughout the procedure.",
    "No unexpected findings were encountered during the colonoscopy.",
    "The examination provided valuable information for the patient's ongoing care.",
    "Scope withdrawal was performed slowly and meticulously to ensure thorough inspection.",
    "No evidence of disease or abnormalities requiring intervention was identified.",
    "The colonoscopy procedure was deemed successful, and no further action is warranted.",
    "The examination provided clarity regarding the patient's gastrointestinal health.",
    "No signs of infection or other complications were noted.",
    "Patient was monitored closely for any signs of adverse reactions to sedation.",
    "The colonoscopy findings were documented accurately in the medical record.",
    "No significant abnormalities were detected that require immediate intervention.",
    "The procedure team ensured patient safety and comfort throughout the examination.",
    "Colonoscopy results were communicated to the patient in a clear and understandable manner.",
    "No evidence of polyps or other lesions requiring removal was observed.",
    "The examination was performed with attention to detail and thoroughness.",
    "The colonoscopy findings provided valuable information for the patient's treatment plan.",
    "Patient's recovery from sedation was monitored closely to ensure a smooth transition.",
    "The procedure was completed without complications, and no further action is necessary.",
    "The colonoscopy results were reviewed and confirmed by the interpreting physician.",
    "Patient's medical history and clinical presentation were taken into consideration during the examination.",
    "No evidence of bleeding or other signs of pathology was observed.",
    "The colonoscopy procedure was deemed successful, and the patient was discharged home.",
    "The examination provided valuable insights into the patient's gastrointestinal health.",
    "No adverse events occurred that required intervention during the procedure.",
    "The colonoscopy findings were consistent with a normal examination, and no abnormalities were detected.",
    "Patient's comfort and well-being were prioritized throughout the examination.",
    "Scope insertion and withdrawal were performed smoothly and without difficulty.",
    "The colonoscopy results were communicated to the patient's referring physician for further management.",
    "No abnormalities requiring urgent attention were identified during the examination.",
    "The procedure team ensured adherence to infection control protocols throughout the examination.",
    "Colonoscopy results were documented clearly and concisely in the medical record.",
    "The examination provided valuable information for the patient's ongoing care and management.",
    "No evidence of inflammation or other pathological changes requiring intervention was observed.",
    "The colonoscopy procedure was completed without incident, and the patient tolerated it well.",
    "The examination provided reassurance regarding the patient's gastrointestinal health, and no further action is needed."
]
procedure_tolerance_pool = [
    "Procedure was well-tolerated by the patient.",
    "The patient remained comfortable and cooperative throughout the examination.",
    "There were no complaints of discomfort or pain during the procedure.",
    "Patient's tolerance to the procedure was excellent.",
    "The patient did not experience any significant discomfort during the examination.",
    "Minimal discomfort was reported by the patient during the procedure.",
    "The patient was able to tolerate the procedure without difficulty.",
    "No signs of distress or discomfort were observed throughout the examination.",
    "Patient's pain level remained low throughout the colonoscopy.",
    "The procedure was conducted without causing undue discomfort to the patient.",
    "Patient's cooperation during the procedure was excellent.",
    "The patient remained calm and composed during the examination.",
    "No evidence of anxiety or agitation was observed during the procedure.",
    "The patient's comfort was prioritized throughout the colonoscopy.",
    "Patient's tolerance to the procedure was deemed satisfactory.",
    "The patient did not experience any adverse reactions to sedation.",
    "The procedure team ensured patient comfort throughout the examination.",
    "Patient's vital signs remained stable, indicating good tolerance to the procedure.",
    "There were no signs of intolerance or adverse reactions to sedation.",
    "Patient's pain level was well-managed throughout the colonoscopy.",
    "The patient was able to communicate effectively throughout the examination.",
    "No signs of distress or discomfort were noted during the procedure.",
    "The patient's comfort and well-being were prioritized throughout the colonoscopy.",
    "Patient's cooperation with the procedure was excellent.",
    "The procedure was conducted smoothly without causing undue discomfort to the patient.",
    "Minimal discomfort was reported by the patient during the examination.",
    "Patient's anxiety level remained low throughout the procedure.",
    "The patient was able to tolerate the procedure without difficulty.",
    "No significant discomfort was reported by the patient during the colonoscopy.",
    "Patient's cooperation and tolerance to the procedure were exemplary.",
    "The colonoscopy procedure was well-tolerated by the patient.",
    "The patient did not experience any discomfort or pain during the examination.",
    "Minimal discomfort was reported by the patient, which was well-managed.",
    "Patient's tolerance to the procedure was deemed satisfactory.",
    "No signs of distress or discomfort were observed throughout the examination.",
    "The patient remained calm and composed during the colonoscopy.",
    "Patient's cooperation with the procedure was excellent.",
    "The procedure team ensured patient comfort and safety throughout the examination.",
    "Patient's vital signs remained stable, indicating good tolerance to the procedure.",
    "There were no signs of intolerance or adverse reactions to sedation.",
    "Patient's pain level was well-controlled throughout the colonoscopy.",
    "The patient was able to communicate effectively throughout the examination.",
    "No evidence of anxiety or agitation was observed during the procedure.",
    "Patient's comfort and well-being were prioritized throughout the colonoscopy.",
    "The patient's cooperation during the procedure was exceptional.",
    "The colonoscopy procedure was conducted smoothly without causing undue discomfort to the patient.",
    "Minimal discomfort was reported by the patient, which was well-managed.",
    "Patient's anxiety level remained low throughout the examination.",
    "No significant discomfort was reported by the patient during the procedure.",
    "Patient's cooperation and tolerance to the procedure were exemplary.",
    "The colonoscopy procedure was well-tolerated by the patient.",
    "The patient did not experience any discomfort or pain during the examination.",
    "Minimal discomfort was reported by the patient, which was well-managed.",
    "Patient's tolerance to the procedure was deemed satisfactory.",
    "No signs of distress or discomfort were observed throughout the examination.",
    "The patient remained calm and composed during the colonoscopy.",
    "Patient's cooperation with the procedure was excellent.",
    "The procedure team ensured patient comfort and safety throughout the examination.",
    "Patient's vital signs remained stable, indicating good tolerance to the procedure.",
    "There were no signs of intolerance or adverse reactions to sedation.",
    "Patient's pain level was well-controlled throughout the colonoscopy.",
    "The patient was able to communicate effectively throughout the examination.",
    "No evidence of anxiety or agitation was observed during the procedure.",
    "Patient's comfort and well-being were prioritized throughout the colonoscopy.",
    "The patient's cooperation during the procedure was exceptional.",
    "The colonoscopy procedure was conducted smoothly without causing undue discomfort to the patient.",
    "Minimal discomfort was reported by the patient, which was well-managed.",
    "Patient's anxiety level remained low throughout the examination.",
    "No significant discomfort was reported by the patient during the procedure.",
    "Patient's cooperation and tolerance to the procedure were exemplary.",
    "The colonoscopy procedure was well-tolerated by the patient.",
    "The patient did not experience any discomfort or pain during the examination.",
    "Minimal discomfort was reported by the patient, which was well-managed.",
    "Patient's tolerance to the procedure was deemed satisfactory.",
    "No signs of distress or discomfort were observed throughout the examination.",
    "The patient remained calm and composed during the colonoscopy.",
    "Patient's cooperation with the procedure was excellent.",
    "The procedure team ensured patient comfort and safety throughout the examination.",
    "Patient's vital signs remained stable, indicating good tolerance to the procedure.",
    "There were no signs of intolerance or adverse reactions to sedation.",
    "Patient's pain level was well-controlled throughout the colonoscopy.",
    "The patient was able to communicate effectively throughout the examination.",
    "No evidence of anxiety or agitation was observed during the procedure.",
    "Patient's comfort and well-being were prioritized throughout the colonoscopy.",
    "The patient's cooperation during the procedure was exceptional.",
    "The colonoscopy procedure was conducted smoothly without causing undue discomfort to the patient.",
    "Minimal discomfort was reported by the patient, which was well-managed.",
    "Patient's anxiety level remained low throughout the examination.",
    "No significant discomfort was reported by the patient during the procedure.",
    "Patient's cooperation and tolerance to the procedure were exemplary.",
    "The colonoscopy procedure was well-tolerated by the patient.",
    "The patient did not experience any discomfort or pain during the examination.",
    "Minimal discomfort was reported by the patient, which was well-managed.",
    "Patient's tolerance to the procedure was deemed satisfactory.",
    "No signs of distress or discomfort were observed throughout the examination.",
    "The patient remained calm and composed during the colonoscopy.",
    "Patient's cooperation with the procedure was excellent.",
    "The procedure team ensured patient comfort and safety throughout the examination.",
    "Patient's vital signs remained stable, indicating good tolerance to the procedure.",
    "There were no signs of intolerance or adverse reactions to sedation.",
    "Patient's pain level was well-controlled throughout the colonoscopy.",
    "The patient was able to communicate effectively throughout the examination.",
    "No evidence of anxiety or agitation was observed during the procedure.",
    "Patient's comfort and well-being were prioritized throughout the colonoscopy.",
    "The patient's cooperation during the procedure was exceptional.",
    "The colonoscopy procedure was conducted smoothly without causing undue discomfort to the patient.",
    "Minimal discomfort was reported by the patient, which was well-managed.",
    "Patient's anxiety level remained low throughout the examination.",
    "No significant discomfort was reported by the patient during the procedure.",
    "Patient's cooperation and tolerance to the procedure were exemplary."
]

def generate_report(num_reports):
    for report_num in range(num_reports):
        # Generate fake patient information
        patient_name = fake.name()
        mrn = fake.random_number(digits=7)
        dob = fake.date_of_birth(minimum_age=30, maximum_age=90).strftime('%m/%d/%Y')
        gender = fake.random_element(elements=('Male', 'Female'))
        procedure_date = fake.date_this_year().strftime('%m/%d/%Y')
        physician_name = fake.name()
        room = fake.random_element(elements=('Room 1', 'Room 2', 'Room 3', 'Room 4'))
        referring_physician = fake.name()

        # Randomly select values from each pool
        indications = random.sample(indications_pool, k=1)
        medications = random.sample(medications_pool, k=2)
        complications = random.sample(complications_pool, k=3)
        findings = random.sample(findings_pool, k=4)
        impression = random.choice(impression_pool)
        recommendations = random.sample(recommendations_pool, k=3)
        cpt_procedure_codes = random.sample(cpt_procedure_codes_pool, k=1)
        icd_diagnosis_codes = random.sample(icd_diagnosis_codes_pool, k=2)
        attending_participation = random.sample(attending_participation_pool, k=3)
        procedure_intro = random.choice(procedure_intro_pool)
        procedure_success = random.choice(procedure_success_pool)
        procedure_tolerance = random.choice(procedure_tolerance_pool)

        # Generate PDF
        doc = SimpleDocTemplate(f'{patient_name}_Colonoscopy_Report_{report_num + 1}.pdf', pagesize=letter)
        
        # Define custom style with larger font size and improved line spacing
        custom_style = ParagraphStyle(
            'CustomStyle',
            fontSize=12,  # Increase font size
            leading=16    # Increase line spacing
        )
        
        story = []

        # Add patient information to PDF
        patient_info = [
            Paragraph("<b>Patient Information:</b>", custom_style),
            Spacer(1, 10),
            Paragraph(f"Name: {patient_name}", custom_style),
            Paragraph(f"MRN: {mrn}", custom_style),
            Paragraph(f"DOB: {dob}", custom_style),
            Paragraph(f"Gender: {gender}", custom_style),
            Spacer(1, 10),
            Paragraph("<b>Procedure Details:</b>", custom_style),
            Spacer(1, 10),
            Paragraph(f"Procedure: Colonoscopy", custom_style),
            Paragraph(f"Date: {procedure_date}", custom_style),
            Paragraph(f"Attending Physician: {physician_name}", custom_style),
            Paragraph(f"Referring MD: {referring_physician}", custom_style),
            Paragraph(f"Room: {room}", custom_style),
            Spacer(1, 10),
            Paragraph("<b>Procedure:</b>", custom_style),
            Spacer(1, 10),
            Paragraph(f"• {procedure_intro}", custom_style),
            Paragraph(f"• {procedure_success}", custom_style),
            Paragraph(f"• {procedure_tolerance}", custom_style),
            Spacer(1, 10)
        ]
        story.extend(patient_info)

        # Add procedure details to PDF
        procedure_details = [
            Paragraph("<b>Indications:</b>", custom_style)
        ]
        for indication in indications:
            procedure_details.append(Paragraph(f"• {indication}", custom_style))
        procedure_details.extend([
            Spacer(1, 10),
            Paragraph("<b>Medications:</b>", custom_style)
        ])
        for medication in medications:
            procedure_details.append(Paragraph(f"• {medication}", custom_style))
        procedure_details.extend([
            Spacer(1, 10),
            Paragraph("<b>Complications:</b>", custom_style),
        ])
        if complications:
            for complication in complications:
                procedure_details.append(Paragraph(f"• {complication}", custom_style))
        else:
            procedure_details.append(Paragraph("• No complications.", custom_style))
        procedure_details.append(Spacer(1, 10))
        story.extend(procedure_details)

        # Add findings to PDF
        findings_section = [
            Paragraph("<b>Findings:</b>", custom_style)
        ]
        for finding in findings:
            findings_section.append(Paragraph(f"• {finding}", custom_style))
        findings_section.append(Spacer(1, 10))
        story.extend(findings_section)

        # Add impression to PDF
        impression_section = [
            Paragraph("<b>Impression:</b>", custom_style),
            Paragraph(impression, custom_style),
            Spacer(1, 10)
        ]
        story.extend(impression_section)

        # Add recommendations to PDF
        recommendations_section = [
            Paragraph("<b>Recommendations:</b>", custom_style)
        ]
        for recommendation in recommendations:
            recommendations_section.append(Paragraph(f"• {recommendation}", custom_style))
        recommendations_section.append(Spacer(1, 10))
        story.extend(recommendations_section)

        # Add CPT procedure codes to PDF
        cpt_codes_section = [
            Paragraph("<b>CPT Procedure Code(s):</b>", custom_style)
        ]
        for cpt_code in cpt_procedure_codes:
            cpt_codes_section.append(Paragraph(f"• {cpt_code}", custom_style))
        cpt_codes_section.append(Spacer(1, 10))
        story.extend(cpt_codes_section)

        # Add ICD-10 diagnosis codes to PDF
        icd_codes_section = [
            Paragraph("<b>ICD-10 Diagnosis Code(s):</b>", custom_style)
        ]
        for icd_code in icd_diagnosis_codes:
            icd_codes_section.append(Paragraph(f"• {icd_code}", custom_style))
        icd_codes_section.append(Spacer(1, 10))
        story.extend(icd_codes_section)

        # Add attending participation to PDF
        attending_participation_section = [
            Paragraph("<b>Attending Participation:</b>", custom_style),
        ]
        for participation in attending_participation:
            attending_participation_section.append(Paragraph(participation, custom_style))
        attending_participation_section.append(Spacer(1, 10))
        story.extend(attending_participation_section)

        # Build PDF
        doc.build(story)

# Generate reports
generate_report(500)